config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "todos#index"

  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, :status, :priority, :start_time, :end_time, presence: true
  
  enum priority: {"high": 1, "normal": 2, "low": 3}
  enum status: {"pending": 1, "processing": 2, "done": 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :find_todo, only: [:edit, :update, :show, :destroy]


  def index
    @todo = Todo.all.sort_by{|i| i.created_at}
  end
  
  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to root_path, notice: "新增成功"
    else
      redirect_to new_todo_path
    end
  end

  def edit
  end 

  def show
  end

  def update
    if @todo.update(todo_params)
      redirect_to root_path, notice: "更新成功"
    else
      redirect_to edit_todo_path
    end
  
  end 

  def destroy
    @todo.destroy
    redirect_to root_path, notice: "刪除成功"
  end

  private

  def find_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:title, :content, :status, :priority, :start_time, :end_time)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Copperman</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>

  <body>
  <%= render "shared/nav" %>
  <%= render "shared/flash" if notice%>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<%= notice %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Todo List", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse flex-row-reverse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
  </div>
</nav>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <%= f.label :title, "標題" %>
  <%= f.text_field :title %>

  <%= f.label :start_time, "開始時間" %>
  <%= f.datetime_local_field :start_time %>

  <%= f.label :end_time, "結束時間" %>
  <%= f.datetime_local_field :end_time %>

  <%= f.label :content, "內容" %>
  <%= f.text_area :content %>

  <%= f.label :priority, "優先順序" %>
  <%= f.radio_button :priority, "high", checked: true %>
  <%= f.label :priority, "高" %>
  <%= f.radio_button :priority, "normal" %>
  <%= f.label :priority, "中"%>
  <%= f.radio_button :priority, "low" %>
  <%= f.label :priority, "低"%>

  <%= f.label :status, "狀態" %>
  <%= f.select(:status,
                 options_for_select([
                   ["準備中", "pending"],
                   ["進行中", "processing"],
                   ["完成", "done"]
                 ])) %>

  <%= f.submit %>
<% end %>

app/views/todos/edit.html.erb
<h1>編輯 <%= @todo.title %></h1>

<%=render "form" %>

app/views/todos/index.html.erb
<h1>Todo list</h1>

<% @todo.each do |t|%>
  <div>
    <p>標題： <%= t.title %></p>
    <p>內容： <%= t.content %></p>
    <p>狀態： <%= t.status %></p>
    <p>優先順序： <%= t.priority %></p>
    <p>開始於： <%= t.start_time %></p>
    <p>結束於： <%= t.end_time %></p>
  </div>
    <%= link_to "編輯", edit_todo_path(t) %>
    <%= link_to "刪除", todo_path(t), method: :delete, data: {confirm: "確定刪除?"} %>
<% end %>

<%= link_to "新增", new_todo_path %>

app/views/todos/new.html.erb
<h1>新增Todo list</h1>

<%=render "form" %>